version: 2.1
executors:
  python-executor:
    docker:
      - image: cimg/python:3.9.9
orbs:
    python: circleci/python@2.1.1
    aws-cli: circleci/aws-cli@2.0.3
    browser-tools: circleci/browser-tools@1.4.8
jobs:
  builds:
    working_directory: ~/Flask-calculator
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt   
      - run:
          name: Build Script
          command: |
            pwd
            chmod 777 build.sh
            ls -la
            ./build.sh
            pwd
            ls -la     
      - run: 
          name: Python Version
          command: python3 --version
      - run: 
          name: Test
          command: |
            cd /home/circleci
            ls -lrth
      - run:
          name: Artifact Archiving
          command: |
            pwd
            chmod 777 artifact.sh
            ls -la
            ./artifact.sh
  deploy:
    working_directory: ~/Flask-calculator
    docker:
      - image: cimg/azure:2023.09
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            cat /etc/os-release
            sudo mkdir -p /var/lib/apt/lists/partial
            sudo chmod 755 /var/lib/apt/lists/partial
            sudo rm /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
      - run:
          name: Azure App Service Deploy
          command: |
            pwd
            chmod 777 artifact.sh
            ls -la
            ./artifact.sh
            pwd 
            ls -lrth
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az account set --subscription $AZURE_SUBSCRIPTION_ID
            az webapp deployment source config-zip -g $AZURE_RG_NAME -n $AZURE_WEBAPP_NAME --src *.zip
            az webapp up -n $AZURE_WEBAPP_NAME -g $AZURE_RG_NAME
  
  run_tests:
    working_directory: ~/Flask-calculator
    docker:
      - image: "cimg/python:3.9.9"
      - image: cimg/node:20.4.0-browsers
    steps: 
      - checkout 
      - python/install-packages: 
          pkg-manager: pip
      - aws-cli/setup
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          name: Run Selenium Tests
          command: |
            whereis chrome
            pwd
            ls -lrtha
            chmod 777 build.sh
            ./build.sh 
            ls -lrtha
            cd tests
            chmod 777 selenium_driver_code.py
            python selenium_driver_code.py
workflows:
  build_and_test_deploy:
    jobs:
      - builds:
          context: Jira           
      - deploy:
          requires:
            - builds
          context: Jira
      - run_tests:
          requires:
            - deploy
